# Generated by Django 4.0.3 on 2022-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_type',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incident_type',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
